package com.bibli.bd.dao;

import com.bibli.bd.base.BaseClassifyingDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the classifying table.
 * Any customizations belong here.
 */
public class ClassifyingDAO extends BaseClassifyingDAO {
}