package com.bibli.bd.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the bd table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="bd"
 */
public abstract class BaseBd  implements Serializable {

	public static String PROP_EDITOR = "Editor";
	public static String PROP_ILLUS_FIRSTNAME = "IllusFirstname";
	public static String PROP_COLOR_NAME = "ColorName";
	public static String PROP_AUTHOR_NAME = "AuthorName";
	public static String PROP_ILLUS_NAME = "IllusName";
	public static String PROP_LANGUAGE = "Language";
	public static String PROP_AUTHOR_FIRSTNAME = "AuthorFirstname";
	public static String PROP_ISBN = "Isbn";
	public static String PROP_COLOR_FIRSTNAME = "ColorFirstname";
	public static String PROP_PUBLISH_DATE = "PublishDate";
	public static String PROP_TITLE = "Title";
	public static String PROP_SERIE = "Serie";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.String _isbn;

	// fields
	private java.lang.String _serie;
	private java.lang.String _editor;
	private java.lang.String _colorName;
	private java.lang.String _title;
	private java.lang.String _colorFirstname;
	private java.lang.String _authorName;
	private java.lang.String _authorFirstname;
	private java.lang.String _illusFirstname;
	private java.lang.String _language;
	private java.lang.String _illusName;
	private java.util.Date _publishDate;


	// constructors
	public BaseBd () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseBd (java.lang.String _isbn) {
		this.setIsbn(_isbn);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseBd (
		java.lang.String _isbn,
		java.lang.String _editor,
		java.lang.String _title,
		java.lang.String _authorName,
		java.lang.String _authorFirstname,
		java.lang.String _illusFirstname,
		java.lang.String _language,
		java.lang.String _illusName,
		java.util.Date _publishDate) {

		this.setIsbn(_isbn);
		this.setEditor(_editor);
		this.setTitle(_title);
		this.setAuthorName(_authorName);
		this.setAuthorFirstname(_authorFirstname);
		this.setIllusFirstname(_illusFirstname);
		this.setLanguage(_language);
		this.setIllusName(_illusName);
		this.setPublishDate(_publishDate);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="isbn"
     */
	public java.lang.String getIsbn () {
		return _isbn;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _isbn the new ID
	 */
	public void setIsbn (java.lang.String _isbn) {
		this._isbn = _isbn;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: serie
	 */
	public java.lang.String getSerie () {
		return _serie;
	}

	/**
	 * Set the value related to the column: serie
	 * @param _serie the serie value
	 */
	public void setSerie (java.lang.String _serie) {
		this._serie = _serie;
	}


	/**
	 * Return the value associated with the column: editor
	 */
	public java.lang.String getEditor () {
		return _editor;
	}

	/**
	 * Set the value related to the column: editor
	 * @param _editor the editor value
	 */
	public void setEditor (java.lang.String _editor) {
		this._editor = _editor;
	}


	/**
	 * Return the value associated with the column: colorName
	 */
	public java.lang.String getColorName () {
		return _colorName;
	}

	/**
	 * Set the value related to the column: colorName
	 * @param _colorName the colorName value
	 */
	public void setColorName (java.lang.String _colorName) {
		this._colorName = _colorName;
	}


	/**
	 * Return the value associated with the column: title
	 */
	public java.lang.String getTitle () {
		return _title;
	}

	/**
	 * Set the value related to the column: title
	 * @param _title the title value
	 */
	public void setTitle (java.lang.String _title) {
		this._title = _title;
	}


	/**
	 * Return the value associated with the column: colorFirstname
	 */
	public java.lang.String getColorFirstname () {
		return _colorFirstname;
	}

	/**
	 * Set the value related to the column: colorFirstname
	 * @param _colorFirstname the colorFirstname value
	 */
	public void setColorFirstname (java.lang.String _colorFirstname) {
		this._colorFirstname = _colorFirstname;
	}


	/**
	 * Return the value associated with the column: authorName
	 */
	public java.lang.String getAuthorName () {
		return _authorName;
	}

	/**
	 * Set the value related to the column: authorName
	 * @param _authorName the authorName value
	 */
	public void setAuthorName (java.lang.String _authorName) {
		this._authorName = _authorName;
	}


	/**
	 * Return the value associated with the column: authorFirstname
	 */
	public java.lang.String getAuthorFirstname () {
		return _authorFirstname;
	}

	/**
	 * Set the value related to the column: authorFirstname
	 * @param _authorFirstname the authorFirstname value
	 */
	public void setAuthorFirstname (java.lang.String _authorFirstname) {
		this._authorFirstname = _authorFirstname;
	}


	/**
	 * Return the value associated with the column: illusFirstname
	 */
	public java.lang.String getIllusFirstname () {
		return _illusFirstname;
	}

	/**
	 * Set the value related to the column: illusFirstname
	 * @param _illusFirstname the illusFirstname value
	 */
	public void setIllusFirstname (java.lang.String _illusFirstname) {
		this._illusFirstname = _illusFirstname;
	}


	/**
	 * Return the value associated with the column: language
	 */
	public java.lang.String getLanguage () {
		return _language;
	}

	/**
	 * Set the value related to the column: language
	 * @param _language the language value
	 */
	public void setLanguage (java.lang.String _language) {
		this._language = _language;
	}


	/**
	 * Return the value associated with the column: illusName
	 */
	public java.lang.String getIllusName () {
		return _illusName;
	}

	/**
	 * Set the value related to the column: illusName
	 * @param _illusName the illusName value
	 */
	public void setIllusName (java.lang.String _illusName) {
		this._illusName = _illusName;
	}


	/**
	 * Return the value associated with the column: publishDate
	 */
	public java.util.Date getPublishDate () {
		return _publishDate;
	}

	/**
	 * Set the value related to the column: publishDate
	 * @param _publishDate the publishDate value
	 */
	public void setPublishDate (java.util.Date _publishDate) {
		this._publishDate = _publishDate;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.bibli.bd.base.BaseBd)) return false;
		else {
			com.bibli.bd.base.BaseBd mObj = (com.bibli.bd.base.BaseBd) obj;
			if (null == this.getIsbn() || null == mObj.getIsbn()) return false;
			else return (this.getIsbn().equals(mObj.getIsbn()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIsbn()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIsbn().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}