package com.bibli.bd.base;

import java.io.Serializable;

import org.json.JSONException;
import org.json.JSONObject;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the classifying table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="classifying"
 */
public abstract class BaseClassifying  implements Serializable {

	public static String PROP_FIELD = "Field";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private com.bibli.bd.ClassifyingPK _id;

	// fields
	private java.lang.String _field;


	// constructors
	public BaseClassifying () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseClassifying (com.bibli.bd.ClassifyingPK _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseClassifying (
		com.bibli.bd.ClassifyingPK _id,
		java.lang.String _field) {

		this.setId(_id);
		this.setField(_field);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     */
	public com.bibli.bd.ClassifyingPK getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (com.bibli.bd.ClassifyingPK _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: field
	 */
	public java.lang.String getField () {
		return _field;
	}

	/**
	 * Set the value related to the column: field
	 * @param _field the field value
	 */
	public void setField (java.lang.String _field) {
		this._field = _field;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.bibli.bd.base.BaseClassifying)) return false;
		else {
			com.bibli.bd.base.BaseClassifying mObj = (com.bibli.bd.base.BaseClassifying) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}
	
	public JSONObject toJSON() throws JSONException {
		JSONObject JSONClassifying = new JSONObject();
		JSONClassifying.put("user", this.getId().getUser().toJSON());
		JSONClassifying.put("position", this.getId().getPosition());
		JSONClassifying.put("field", this.getField());
		
		return JSONClassifying;
	}

}